### PR TITLE
Hi, here's paklongwu1006 from transifex!

### PR DESCRIPTION
**Pull request by alexanderlime**
I updated some changes I just made.

### CODE REVIEW

**Comment by zhaofengli** [comment]
Hi there! Thanks for the patches! However, could you squash the commits before I merge them?

**Comment by alexanderlime** [comment]
"Squash"?

**Comment by ricordisamoa** [comment]
http://git-scm.com/book/it/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by alexanderlime** [comment]
OMG I'm ruinning the PR... Can't make this I need help XD

**Comment by zhaofengli** [comment]
There's a dirty way to "squash" them:
- `git reset 3df1a29` to throw away your commits while keeping the changes in the workspace
- `git add` the files and commit as usual
- `git push -f` to forcibly rewrite the history on remote

**Comment by alexanderlime** [comment]
Done :D

**Pull request closed without merging**
